from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Optional, Dict, Any
from sqlalchemy.orm import Session
import models, auth, database
from services import email_service
from services.gemini_assistant import parse_intent
from routers import documents as documents_router

router = APIRouter(tags=["recruiter_assistant"])

class ChatRequest(BaseModel):
    message: str

class ChatResponse(BaseModel):
    reply: str
    pending_action: Optional[Dict[str, Any]] = None

class ConfirmRequest(BaseModel):
    application_id: int
    salary: str
    email: str

class ConfirmResponse(BaseModel):
    success: bool
    message: str

@router.post("/assistant/chat", response_model=ChatResponse)
def chat(request: ChatRequest, current_user: models.User = Depends(auth.role_required([models.Role.RECRUITER])), db: Session = Depends(database.get_db)):
    # Use Gemini to parse intent (simple placeholder context)
    intent_data = parse_intent(request.message, {})
    if intent_data.get("error"):
        raise HTTPException(status_code=400, detail=intent_data["error"])
    intent = intent_data.get("intent")
    reply = intent_data.get("reply", "")
    pending_action = None
    if intent == "GENERATE_OFFER":
        candidate_name = intent_data.get("candidate_name")
        job_title = intent_data.get("job_title")
        salary = intent_data.get("salary") or ""
        # Find matching application
        application = (
            db.query(models.Application)
            .join(models.Candidate)
            .join(models.Job)
            .filter(models.Candidate.name == candidate_name, models.Job.title == job_title)
            .first()
        )
        if not application:
            reply = f"Could not find an application for {candidate_name} - {job_title}."
        else:
            reply = f"Ready to generate offer for {candidate_name} ({job_title}) with salary {salary}."
            pending_action = {
                "application_id": application.id,
                "salary": salary,
                "email": application.candidate.email,
            }
    else:
        # Fallback echo reply if not generated by Gemini
        if not reply:
            reply = f"Assistant: {request.message}"
    return ChatResponse(reply=reply, pending_action=pending_action)

@router.post("/assistant/confirm", response_model=ConfirmResponse)
def confirm(request: ConfirmRequest, current_user: models.User = Depends(auth.role_required([models.Role.RECRUITER])), db: Session = Depends(database.get_db)):
    # Generate offer letter PDF using existing logic
    try:
        result = documents_router.generate_offer_letter(request.application_id, request.salary, current_user, db)
    except Exception as e:
        raise HTTPException(status_code=500, detail="Failed to generate offer letter")
    # Send email with offer letter link
    file_url = result.get("file_url")
    email_body = f"<p>Please find your offer letter here: <a href='{file_url}'>Offer Letter</a></p>"
    email_sent = email_service.send_email(to_email=request.email, subject="Your Offer Letter", html_body=email_body)
    if not email_sent:
        return ConfirmResponse(success=False, message="Offer generated but failed to send email.")
    return ConfirmResponse(success=True, message="Offer letter generated and email sent successfully.")
